### ISSUE TITLE
TreeViewColumn::new_with_attributes

### ISSUE THREAD

**Issue by mehmooda** [gtk-rs/gtk3-rs#226]
If your following the [GTK3 TreeView documentation](https://developer.gnome.org/gtk3/stable/TreeWidget.html) then gtk_tree_view_column_new_with_attributes is used.

Its a bit of a stumbling block for those new to GTK to figure out the order of pack_start and add_attribute.

**Comment by sdroege** [comment]
That function is a bit hard to bind. From what I can see it would have to be re-implemented around the existing bound API, or instead of that you'd use the [TreeViewColumnBuilder](https://gtk-rs.org/docs/gtk/struct.TreeViewColumnBuilder.html) (but that doesn't include the cell renderer so `pack_start()` would still be necessary AFAIU).

**Comment by bilelmoussaoui** [comment]
It can be copied from https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/tree_view_column.rs#L10
